"""
tools.py — Sandboxed, blocklist-validated tools available to the BhavAI agent.

Key addition over v1
--------------------
`append_chunk(path, chunk, done)` — purpose-built for the 4096-token limit.
Instead of writing an entire file in one shot (which truncates the response),
the LLM writes 50 lines at a time and calls append_chunk repeatedly, setting
done=True only on the last chunk.  This guarantees no single LLM response
ever needs to carry more content than fits in ~1500 tokens.

Git integration
---------------
ensure_git_initialized() is called at the start of every mutating tool so
that all file changes are immediately trackable via `git diff HEAD`.
"""


import re
import subprocess
from pathlib import Path

from bhavai.config import logger, CWD
from bhavai.context import get_folder_tree_string, is_env_file

# ─────────────────────────────────────────────────────────────────────────────
# Security: command blocklist
# ─────────────────────────────────────────────────────────────────────────────

BLOCKED_COMMANDS = [
    "rm", "rmdir", "del", "unlink",
    "shutil.rmtree", "os.remove",
    "format", "mkfs", "drop table",
]


# ─────────────────────────────────────────────────────────────────────────────
# Path sandboxing
# ─────────────────────────────────────────────────────────────────────────────

def validate_path(path_str: str) -> Path:
    """
    Ensures path_str resolves strictly inside CWD.
    Raises ValueError if outside (blocks ../../ traversal, absolute escapes, etc.)
    """
    raw      = Path(path_str)
    resolved = raw.resolve() if raw.is_absolute() else (CWD / raw).resolve()
    try:
        resolved.relative_to(CWD)
    except ValueError:
        raise ValueError(
            f"Access Denied: '{path_str}' → '{resolved}' is outside "
            f"the sandboxed directory '{CWD}'."
        )
    return resolved


# ─────────────────────────────────────────────────────────────────────────────
# Command validation
# ─────────────────────────────────────────────────────────────────────────────

def validate_command(command: str) -> None:
    """Word-boundary regex check against BLOCKED_COMMANDS. Raises on match."""
    cmd_lower = command.lower()
    for blocked in BLOCKED_COMMANDS:
        if re.search(rf"(?:^|\W){re.escape(blocked)}(?:$|\W)", cmd_lower):
            raise ValueError(
                f"Security Violation: blocked operation '{blocked}' in command."
            )


# ─────────────────────────────────────────────────────────────────────────────
# Git initialisation
# ─────────────────────────────────────────────────────────────────────────────

def ensure_git_initialized() -> None:
    """
    Idempotent — runs only once per session (returns immediately if .git/ exists).

    On first call:
      1. Creates a sensible .gitignore if none exists.
      2. git init
      3. Sets local user.name / user.email (avoids "Author identity unknown" errors).
      4. git add .  →  initial commit

    After this, every write/append_chunk call stages the changed file via
    _git_stage() so the user can always run `git diff HEAD` to see what the
    agent changed in red/green diff format.
    """
    git_dir = CWD / ".git"
    if git_dir.exists() and git_dir.is_dir():
        return                                # already initialised

    logger.info("Initialising Git repository in '%s' for change tracking…", CWD)
    try:
        # 1. Default .gitignore
        gi_path = CWD / ".gitignore"
        if not gi_path.exists():
            gi_path.write_text(
                "# Auto-generated by BhavAI\n"
                "__pycache__/\n*.py[cod]\n*.pyo\n"
                ".pytest_cache/\n.mypy_cache/\n"
                ".bhavai/\n.env\n.env.*\n"
                "*.egg-info/\ndist/\nbuild/\n"
                ".venv/\nvenv/\nnode_modules/\n",
                encoding="utf-8",
            )
            logger.info("Created default .gitignore.")

        def _run(*args):
            subprocess.run(
                list(args), cwd=CWD,
                capture_output=True, text=True, check=True,
            )

        # 2–5. Init, identity, stage, commit
        _run("git", "init")
        _run("git", "config", "user.name",  "BhavAI")
        _run("git", "config", "user.email", "bhavai@local.ai")
        _run("git", "add", ".")
        _run("git", "commit", "--allow-empty",
             "-m", "Initial commit — created by BhavAI before first file operation")

        logger.info("Git repository ready.")

    except subprocess.CalledProcessError as exc:
        logger.error("Git init command failed: cmd=%s stdout=%s stderr=%s",
                     exc.cmd, exc.stdout, exc.stderr)
    except Exception as exc:
        logger.error("Git init unexpected error: %s", exc)


def _git_stage(resolved: Path) -> None:
    """Silently stage a file so it appears in git diff HEAD. Best-effort."""
    try:
        subprocess.run(
            ["git", "add", str(resolved)],
            cwd=CWD, capture_output=True, text=True, check=False,
        )
    except Exception as exc:
        logger.debug("_git_stage silent error: %s", exc)


# ─────────────────────────────────────────────────────────────────────────────
# Tool: list_folder
# ─────────────────────────────────────────────────────────────────────────────

def list_folder(path: str = ".") -> str:
    """
    Returns the gitignore-aware folder tree for a directory inside CWD.
    """
    logger.info("list_folder('%s')", path)
    resolved = validate_path(path)
    if not resolved.exists():
        return f"Error: '{path}' does not exist."
    if not resolved.is_dir():
        return f"Error: '{path}' is a file, not a directory."
    return get_folder_tree_string(resolved)


# ─────────────────────────────────────────────────────────────────────────────
# Tool: read_file
# ─────────────────────────────────────────────────────────────────────────────

def read_file(path: str) -> str:
    """
    Reads and returns full text content of a file inside CWD.
    Git is initialised first so every workspace is always tracked.

    SECURITY: .env and secrets files are hard-blocked — their content
    is never returned to the agent or sent to the LLM.
    """
    logger.info("read_file('%s')", path)
    ensure_git_initialized()
    resolved = validate_path(path)

    # ── Env / secrets guard ───────────────────────────── #
    if is_env_file(resolved):
        logger.warning("Blocked read attempt on secrets file: '%s'", path)
        return (
            f"Access Denied: '{path}' is an environment/secrets file. "
            f"BhavAI never reads .env or secrets files to protect your credentials. "
            f"If you need to check config, inspect the file yourself manually."
        )

    if not resolved.exists():
        return f"Error: '{path}' does not exist."
    if not resolved.is_file():
        return f"Error: '{path}' is a directory."
    try:
        return resolved.read_text(encoding="utf-8")
    except Exception as exc:
        logger.error("read_file('%s'): %s", path, exc)
        return f"Error reading '{path}': {exc}"


# ─────────────────────────────────────────────────────────────────────────────
# Tool: write_file
# ─────────────────────────────────────────────────────────────────────────────

def write_file(path: str, content: str) -> str:
    """
    Creates or overwrites a file.  Use ONLY for short content (< 60 lines).
    For longer files, use append_chunk instead to avoid 4096-token cutoff.
    """
    logger.info("write_file('%s', %d chars)", path, len(content))
    ensure_git_initialized()
    resolved = validate_path(path)

    # ── Env / secrets guard ───────────────────────────── #
    if is_env_file(resolved):
        logger.warning("Blocked write attempt on secrets file: '%s'", path)
        return (
            f"Access Denied: '{path}' is an environment/secrets file. "
            f"BhavAI never writes to .env or secrets files."
        )

    # Warn agent if it ignores the 60-line guideline
    line_count = content.count("\n") + 1
    if line_count > 80:
        logger.warning(
            "write_file called with %d lines on '%s'. "
            "This may hit the 4096-token output limit next call. "
            "Use append_chunk for large files.", line_count, path
        )

    try:
        resolved.parent.mkdir(parents=True, exist_ok=True)
        resolved.write_text(content, encoding="utf-8")
        _git_stage(resolved)
        return (
            f"✓ '{path}' written ({len(content):,} chars, {line_count} lines). "
            f"Use `git diff HEAD` to review."
        )
    except Exception as exc:
        logger.error("write_file('%s'): %s", path, exc)
        return f"Error writing '{path}': {exc}"


# ─────────────────────────────────────────────────────────────────────────────
# Tool: update_file  (legacy — kept for backward compat)
# ─────────────────────────────────────────────────────────────────────────────

def update_file(path: str, content: str, mode: str = "append") -> str:
    """
    Append or overwrite a file.
    Prefer append_chunk for token-safe chunked writing.
    """
    logger.info("update_file('%s', mode='%s', %d chars)", path, mode, len(content))
    ensure_git_initialized()

    if mode not in ("append", "overwrite"):
        return f"Error: mode must be 'append' or 'overwrite', got '{mode}'."
    if mode == "overwrite":
        return write_file(path, content)

    resolved = validate_path(path)
    try:
        resolved.parent.mkdir(parents=True, exist_ok=True)
        with open(resolved, "a", encoding="utf-8") as fh:
            fh.write(content)
        _git_stage(resolved)
        return f"✓ Appended {len(content):,} chars to '{path}'."
    except Exception as exc:
        logger.error("update_file('%s'): %s", path, exc)
        return f"Error updating '{path}': {exc}"


# ─────────────────────────────────────────────────────────────────────────────
# Tool: append_chunk  ← THE KEY FIX FOR THE 4096-TOKEN LIMIT
# ─────────────────────────────────────────────────────────────────────────────

# Tracks which files are currently being written in chunks so we can give
# progress feedback and detect misuse (e.g. done=true on first chunk).
_chunk_state: dict[str, int] = {}   # path → total chars written so far

def append_chunk(path: str, chunk: str, done: bool = False) -> str:
    """
    Appends one chunk of text to a file.

    Parameters
    ----------
    path  : File path relative to CWD (created automatically if it doesn't exist).
    chunk : The text to append.  Should be ≤ 50 lines to stay inside the
            4096-token output budget.
    done  : Set to true ONLY on the final chunk.  Triggers Git staging and
            returns a completion summary.

    How the agent should use this
    -----------------------------
    Large file (e.g. 150-line HTML):
      Call 1:  append_chunk path="index.html" chunk="<lines 1-50>"   done=false
      Call 2:  append_chunk path="index.html" chunk="<lines 51-100>" done=false
      Call 3:  append_chunk path="index.html" chunk="<lines 101-150>" done=true

    The file is created on the first call and appended on every subsequent call.
    Setting done=true stages the file in Git so changes appear in git diff HEAD.
    """
    logger.info("append_chunk('%s', done=%s, %d chars)", path, done, len(chunk))
    ensure_git_initialized()

    resolved = validate_path(path)

    # ── Env / secrets guard ───────────────────────────── #
    if is_env_file(resolved):
        logger.warning("Blocked append_chunk attempt on secrets file: '%s'", path)
        return (
            f"Access Denied: '{path}' is an environment/secrets file. "
            f"BhavAI never writes to .env or secrets files."
        )

    try:
        resolved.parent.mkdir(parents=True, exist_ok=True)

        # First chunk → create/overwrite; subsequent → append
        write_mode = "a" if path in _chunk_state else "w"
        with open(resolved, write_mode, encoding="utf-8") as fh:
            fh.write(chunk)

        prev         = _chunk_state.get(path, 0)
        _chunk_state[path] = prev + len(chunk)
        total        = _chunk_state[path]
        line_count   = chunk.count("\n") + 1

        if done:
            _git_stage(resolved)
            del _chunk_state[path]                  # reset state
            return (
                f"✓ Final chunk written. '{path}' is complete "
                f"({total:,} total chars). "
                f"Run `git diff HEAD` to review all changes."
            )
        else:
            return (
                f"✓ Chunk appended to '{path}' "
                f"({line_count} lines, {len(chunk):,} chars this chunk, "
                f"{total:,} chars total so far). "
                f"Continue with next chunk or set done=true when finished."
            )

    except Exception as exc:
        logger.error("append_chunk('%s'): %s", path, exc)
        # Clean up state on error so next call starts fresh
        _chunk_state.pop(path, None)
        return f"Error in append_chunk for '{path}': {exc}"


# ─────────────────────────────────────────────────────────────────────────────
# Tool: run_command
# ─────────────────────────────────────────────────────────────────────────────

def run_command(command: str) -> str:
    """
    Runs a shell command inside CWD with a 10-second timeout.
    Blocked commands are rejected before execution.
    """
    logger.info("run_command('%s')", command)
    try:
        validate_command(command)
    except ValueError as exc:
        return str(exc)

    import sys
    try:
        proc = subprocess.Popen(
            command, shell=True, cwd=CWD,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        try:
            stdout, stderr = proc.communicate(timeout=10)
        except subprocess.TimeoutExpired:
            logger.warning("Command timed out: '%s'", command)
            if sys.platform == "win32":
                subprocess.run(f"taskkill /F /T /PID {proc.pid}",
                               shell=True, capture_output=True)
            else:
                proc.kill()
            stdout, stderr = proc.communicate()
            parts = ["Error: Command timed out (10 s)."]
            if stdout: parts.append(f"Stdout:\n{stdout}")
            if stderr: parts.append(f"Stderr:\n{stderr}")
            return "\n".join(parts)

        parts = []
        if stdout: parts.append(stdout)
        if stderr: parts.append(f"Stderr:\n{stderr}")
        return "\n".join(parts) if parts else "Command executed with no output."

    except Exception as exc:
        logger.error("run_command('%s'): %s", command, exc)
        return f"Error executing command: {exc}"


# ─────────────────────────────────────────────────────────────────────────────
# Tool dispatch registry
# ─────────────────────────────────────────────────────────────────────────────

TOOL_DISPATCH = {
    "list_folder":   list_folder,
    "read_file":     read_file,
    "write_file":    write_file,
    "update_file":   update_file,    # legacy
    "append_chunk":  append_chunk,   # ← NEW: token-safe chunked writing
    "run_command":   run_command,
    # 'final_answer' is handled directly in agent.py
}

# ─────────────────────────────────────────────────────────────────────────────
# Extended tool registry (tools_extended.py) — merged in here, at the bottom,
# to avoid a circular import (tools_extended imports validate_path / CWD /
# ensure_git_initialized / _git_stage FROM this module).
# ─────────────────────────────────────────────────────────────────────────────

from bhavai.tools_extended import EXTENDED_TOOL_DISPATCH  # noqa: E402

TOOL_DISPATCH.update(EXTENDED_TOOL_DISPATCH)